Feat/#14 Refatoração do codigo pra adicionar gofs
UnBArqDsw2021-2/2021.2_g1_chapa_quente_backend pull request #18
Opened 2022-04-12 16:00 UTC by murilogds

2022-04-14 17:58 UTC, nYCSTs requested changes
Realizar alterações

2022-04-14 17:58 UTC, nYCSTs commented on src/utils/validator.js
> +  if (password.length < 6 && password.length > 16) {
A validação não está sendo feita, essa condição nunca será atendida. 
Precisa trocar de && para ||

2022-04-14 17:58 UTC, nYCSTs commented on src/controller/clienteController.js
> +      await enderecoObject.setFlyWeight(bairro, cidade);
Na ordem que está, um endereço será cadastrado mesmo com a validação de senha dando erro, já que ele ocorre antes da validação. Passar a validação de senha para antes do cadastro de endereço.

2022-04-14 21:45 UTC, nYCSTs approved these changes
LGTM

2022-04-14 22:16 UTC, JPedroCh requested changes
Ao testar com o front, não está sendo possível cadastrar um novo cliente, é recebida a mensagem de que o email já foi utilizado, mesmo não tendo sido.

2022-04-14 23:50 UTC, murilogds commented
> Ao testar com o front, não está sendo possível cadastrar um novo cliente, é recebida a mensagem de que o email já foi utilizado, mesmo não tendo sido.


Na verdade é que o front não tava adaptado pra lidar com outros campos de endereço, fiz um pull request lá pra corrigir isso https://github.com/UnBArqDsw2021-2/2021.2_g1_chapa_quente_frontend/pull/29

2022-04-15 00:19 UTC, JPedroCh approved these changes

2022-04-15 00:29 UTC, merged